version: '3.3'

volumes:
  pg_data:
  static:


services:

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static:/backend_static

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      #- ../frontend/:/app/result_build/
      - static:/frontend_static

  nginx:
    image: nginx:1.19.3
    ports:
      - 8080:80
    volumes:
      - static:/staticfiles/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
