version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: gdemasha/foodgram_backend
    env_file: ../.env
    volumes:
      - static_volume:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: gdemasha/foodgram_frontend
    env_file: ../.env
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 8080:80
    volumes:
      - static_volume:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend